language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - yarn
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - yarn build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN